name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  Hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: echo "Hello world from  github actions"
        shell: bash
  goobay:
    runs-on: ubuntu-latest
    steps:
      - name: goodbay
        run: echo "good bay from github action"
        shell: bash
  date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show actual date
        run: date
        shell: bash
